name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # ou a branch que você quer monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pega o código do repositório
      - uses: actions/checkout@v3

      # 2️⃣ Instala flyctl
      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"
          fly version

      # 3️⃣ Faz deploy
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export PATH="$HOME/.fly/bin:$PATH"
          fly deploy --remote-only --app silent-ipguard
